# -*- coding: utf-8 -*-
"""My Work - 2.0 Linear vs Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yFZyUsxLUflWGAXW_FpLlbxizta2hDxm
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from scipy.special import expit
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

n_samples = 1000
np.random.seed(0)
X = np.random.normal(size=n_samples)
y = (X > 0).astype(np.float)
X[X>0]*=4
X += .3 * np.random.normal(size=n_samples)
X=X[:,np.newaxis]

plt.scatter(X,y)
plt.show()

lm = linear_model.LinearRegression()
model = lm.fit(X,y)

model.score(X,y)

logm =  LogisticRegression(random_state=0, solver='lbfgs', 
                            multi_class='multinomial',max_iter=1000)
model2 = logm.fit(X,y)

model2.score(X,y)