# -*- coding: utf-8 -*-
"""My Work - 1.0 Exercise 1 Weather.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3gpPI5Vl4hnlELDxnZrb8E9czEVeCzf
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn import preprocessing

# %matplotlib inline

dataset = pd.read_csv("Weather.csv")

dataset.shape
#gives the number of rows and columns

dataset.describe()
#gives an overview of the data

plt.scatter(dataset['MaxTemp'],dataset['MinTemp'])
plt.show()



