# -*- coding: utf-8 -*-
"""Apples and Oranges.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1baQCPkCyMo3T6hiC2m3vqz2ouRop1G5H
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC, SVC
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

data = pd.read_csv("apples_and_oranges.csv")

training_set, test_set = train_test_split(data,test_size=0.2, random_state=1)

X_train = training_set.iloc[:,0:2].values
y_train = training_set.iloc[:,2].values
X_test = test_set.iloc[:,0:2].values
y_test = test_set.iloc[:,2].values

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

plt.scatter(X_train[:,0], X_train[:,1], c=y_train,cmap='winter')
plt.show()

#Linear Support Vector Classification

classifier = LinearSVC(random_state=1)
classifier.fit(X_train,y_train)

print(classifier.score(X_test,y_test))

plt.scatter(X_test[:,0],X_test[:,1], c=y_test, cmap='winter')
plt.show
